### ISSUE TITLE
Sample Code of Beebop: Accelerometer Data

### ISSUE THREAD

**Issue by tau90** [ARDroneSDK3/Samples#15]
Hello, I'm trying to use the ARDrone SDK3 with a Bebop Drone for a map reconstruction project and I need to know the drone position (without GPS)·
Does anyone know if the SDK offers an option to read the IMU data (accelerometer)?
I read the SDK documentation but I can't find it.

Thanks.

**Comment by djavan-bertrand** [comment]
Hi tau90, 

You won't get access to the IMU data through the SDK, sorry.

Best regards, 
Djavan

**Comment by djavan-bertrand** [comment]
Hi, 

Instead of the IMU, you can have access to the attitude of the drone on the tree axes.
These data are sent through an ARCommand at around 5hz (this rate is not fixed and may change in the future).
You receive these values in an ARCOMMANDS_Decoder_ARDrone3PilotingStateAttitudeChangedCallback_t .

Regards, 
Djavan
