### ISSUE TITLE
BeBop drifting after takeoff plus missing callbacks

### ISSUE THREAD

**Issue by meavydev** [ARDroneSDK3/Samples#17]
I am writing on Android and have working video plus have stills and video recording.
I can takeoff and control the position via PCMD, but there appears to be some magic setting I am missing, as if you set the flag to zero with zero pitch and roll, the drone seems to drift off.
If I use FreeFlight 3 and then run up my app, then the drone holds position, so I know it is something I am missing, but the samples and documentation seem to lack this basic information...
I have also got callbacks registered for Alert state and media recording for space and they don't get called. At least the battery and flying state callbacks are working.

**Comment by meavydev** [comment]
Mmm so it looks like it was down to not using the ACK versions of the commands, so presumably they were just getting thrown away - but I had to resort to using WireShark and comparing FreeFlight 3 to my app...
How about you actually write some documentation which explains the calls and includes units ;)
V1 / V2 SDKs were more usable than this...

**Comment by mukamalooga** [comment]
Hello. I understand this case is closed, but i sill don't understand that your drifting problem is solved? I have the same problem and really can use some help. Thank You

**Comment by meavydev** [comment]
I would pester Parrot as the samples and documentation is pretty much useless, as you have found.
If what I said doesn't make sense then I guess you have some other problem, perhaps you aren't setting the PCMD flag correctly...

**Comment by heitzek** [comment]
Hello, 

I solved this quite by accident, as you are well saying, the documentation is full of gaps, the problem was I wasn't sending the ARCOMMANDS_Generator_GenerateCommonCommonAllStates command.

If you connect to the bebop with an iPad, disconnect and after that you take off from your code, it will stay steady as long as far as your floor isn't too uniform.

If you want to get the videostreaming from the SkyController instead of directly from the Bebop this is required, dvjavan gave me this info in another thread, so I thought "what if", because it look like to be like a initial setup for the device, and yes, it does, sending that before taking off will avoid your drone to drift, hopefully.

All the best.

**Comment by djavan-bertrand** [comment]
Hi heitzek, 

Thank you very much for your feedback. You're right, you need to send the ARCOMMANDS_Generator_GenerateCommonCommonAllStates to have the bebop hovering well. This command is sent in the BebopDronePiloting (iOS and Android samples), feel free to use it.

Regards, 
Djavan

**Comment by weaversa** [comment]
Is this also true for the RollingSpider / Is there an equivalent command for the RollingSpider?

**Comment by djavan-bertrand** [comment]
Yes, it is true for the RollingSpider too.
You can send the same command to the RollingSpider (it is a common command).

**Comment by mukamalooga** [comment]
So ARCOMMANDS_Generator_GenerateCommonCommonAllStates. Thanks very much for
the info mate.
A try it as soon as i can :)

2015-03-16 13:20 GMT+01:00 heitzek <notifications@github.com>:

**Comment by mukamalooga** [comment]
ARCOMMANDS_Generator_GenerateCommonCommonAllStates works like a charm for me too, thank you. And it also needed to fix the GPS connection i think. Without this i did wait 20 minutes and GPS did nothing. After this, the gps connected in 3 minutes.
Thanks again.
