### ISSUE TITLE
Unix/OS X Video streaming for parrot bebop

### ISSUE THREAD

**Issue by heitzek** [ARDroneSDK3/Samples#7]
Hello, 

as you suggested, I adapted the example of jumping sumo change posture as you suggested and I pasted at the end of the issue. 

It worked, but I'm truly struggling doing the same for video streaming.

No matter what params I change I allways get (even on the pilot example) this message, and I just can't get the video streaming.

Could you bring some help please?

I'm on OS X 10.10 by the way, if you need any other information I can provide it.

[ERR] ARNETWORK_Receiver | 14:12:14:687 | ARNETWORK_Receiver_ThreadRun:265 - data received, error: Insufficient free space in the buffer
[ERR] ARNETWORK_Receiver | 14:12:14:709 | ARNETWORK_Receiver_ThreadRun:265 - data received, error: Insufficient free space in the buffer
[ERR] ARNETWORK_Receiver | 14:12:14:727 | ARNETWORK_Receiver_ThreadRun:265 - data received, error: Insufficient free space in the buffer

---

To connect to a Bebop drone, you can use the JumpingSumoChangePosture sample (Samples/Unix/) and just change the ip address to 192.168.42.1 and change the commands sent (in sendPilotingPosture function) to be a Bebop command.

Typically, you can replace the ARCOMMANDS_Generator_GenerateJumpingSumoPilotingPosture by ARCOMMANDS_Generator_GenerateARDrone3PilotingTakeOff and ARCOMMANDS_Generator_GenerateARDrone3PilotingLanding (a while after the first one). (Don't forget to delete the last parameter posture).

**Comment by heitzek** [comment]
[SOLVED] - very soon I'll post working code.

**Comment by aiden56** [comment]
Hi Heitzek,

Could you let me know how you solved this issue? I'm working on the same thing now.

Thanks!

**Comment by heitzek** [comment]
sure, give me an e-mail and I'll send you full working code

**Comment by aiden56** [comment]
Thanks! It's at0440@bristol.ac.uk!

**Comment by aiden56** [comment]
Hi Heitzek! Have you worked out video streaming from the Bebop?

**Comment by vignesh02** [comment]
Hi Heitzek,

Can you please share the working code of bepop in Linux. email address - vigneshwaran.ganesan@gmail.com

**Comment by pierrezurek** [comment]
Hi, you can check the following example here https://github.com/pierrezurek/Samples/tree/master/Unix/BebopDroneReceiveStream.

**Comment by vignesh02** [comment]
Thanks pierrezurek!!! Do you have code the control the bepop drone from computer.

**Comment by vignesh02** [comment]
Hi,

I am getting this error when compile your code. Can you please help me on
this ?
BebopDroneReceiveStream.c:49:28: fatal error: libARSAL/ARSAL.h: No such
file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.

**Comment by pierrezurek** [comment]
You need to launch the "./SDK3Build.py -t Unix" command in the ARSDKBuildUtils folder before you try to compile the examples. After that step those include files will be found by make in the ARSDKBuildUtils/Targets/Unix/Install/include folder.

**Comment by djavan-bertrand** [comment]
The sample is now part of the official samples : [BebopDroneReceiveStream](https://github.com/ARDroneSDK3/Samples/tree/master/Unix/BebopDroneReceiveStream)

Enjoy !

**Comment by vignesh02** [comment]
Hi Djavan-bertrand,

Still i am getting the same error

Steps taken from me
1. Created the folder name SDK and inside the SDK folder clone the actual code from github https://github.com/ARDroneSDK3/ARSDKBuildUtils.git
2. After it was downloaded then moved into ARSDKBuildUtils folder and gave below command 
./SDK3Build.py -t Unix and build took 8 minutes to complete
3. Came out of the ARSDKBuildUtils and SDK folder and downloaded the working version of Bepop for Unix from Git Hub https://github.com/ARDroneSDK3/Samples.git
4. cd /Samples/Unix/BebopDroneReceiveStream and ran the make command
5. got the same error

BebopDroneReceiveStream.c:49:28: fatal error: libARSAL/ARSAL.h: No such
file or directory
 #include <libARSAL/ARSAL.h>
                            ^
compilation terminated.

Can you please tell what steps am i missing here to run your program.

Can you please give us some code for capturing a picture through the camera. There are 4 parameters that needs to be passed, we would like some sample code for the 4th parameter - storage ID. Otherwise, if you have some code for image capture, please share that with us.

**Comment by djavan-bertrand** [comment]
Hello vignesh02,

You should only clone https://github.com/ARDroneSDK3/ARSDKBuildUtils.git. 
After running ./SDK3Build.py -t Unix, you should have all the sources, including Samples (at the same path than ARSDKBuildUtils, ARSAL, ARCommands and other libs folders).

To sum up (starting in your newly created SDK folder) : 
* git clone https://github.com/ARDroneSDK3/ARSDKBuildUtils.git
* cd ARSDKBuildUtils
* ./SDK3Build.py -t Unix
* cd ../Samples/Unix/BebopDroneReceiveStream
* make
* make run

Hope this helps,
Djavan

**Comment by vignesh02** [comment]
Hi Djavan-bertrand,
Sure will try this option today. Do you sample code to capture image(not video)

**Comment by Cashews54** [comment]
Has anyone had luck with using iOS 8 hardware accelerated decoding (covered in WWDC 513) to handle the H.264 Bebop stream?  I'm pretty new to video decoding but here is my attempt.  I don't get any errors so I'm not sure if I'm messing up Apple's APIs or if I'm misinterpreting the Bebop stream.

1) In the frameCompleteCallback method I pass the uint8_t *frame and uint32_t frameSize to a custom method of my own. 
2) In that method, I read the NALU's start header 0x00 00 00 01 YY, where YY is the type of NALU packet.  (It seems like there are two kinds of frames I receive in frameCompleteCallback.  One has 3 NALUs in it: SPS, PPS followed by a coded slice of an IDR picture.  The other only has 1 NALU: a coded slice of a non-IDR picture.  With the former type, I remove the SPS and PPS before sending the IDR picture NALU to my display layer.)
3) If the NALU has SPS or PPS parameters, I save those and apply them to my AVSampleBufferDisplayLayer.
4) If the NALU is a slice of a VCL picture, I replace the first 4 bytes with the length of the entire NALU (not including its header in the length) and package it in a CMBlockBuffer.
5) I wrap the CMBlockBuffer into a CMSampleBuffer and queue that onto my AVSampleBufferDisplayLayer.

So am I missing any steps here?  Am I wrong in assuming that one NALU will never be spread across more than one frame?  Because I sometimes receive frames with the NALU start code = 0 (Unspecified non-VCL) and I'm not sure what they are.  Should I be getting some decode/display timing information from the NALUs before sending them to the display layer?  Are there any emulation prevention bytes I should be ignoring?

Thanks, and any help is appreciated!

**Comment by vignesh02** [comment]
Hi Djavan-bertrand,

I was able to run the program without any issue and video also was streaming.good.

Few Queries
Whether we can stream the video in the HTML5.
What the port that video is stream so that can listen to that port.

**Comment by djavan-bertrand** [comment]
Hi Cashews54, 

You are right : there are two types of frame that you receive : the i-frames and the p-frames.
I-frames contains 3 NALUs (each of them are separated by the header 00 00 00 01): 
* the Sequence Parameter Set
* the Picture Parameter Set
* the frame
P-frames contains only the NALUs of the frame.

Basically, to use the hardware decoding : 
* Extract the sps and pps (without their headers)
* Create a CMVideoFormatDescriptionRef with the sps and pps
* Change the header of the frame NAL with its length (length without the header)
* Create a CMBlockBufferRef with the frame (the 7th parameter block length is the length of the block including the header)
* Create a CMSampleTimingInfo
* Create your CMSampleBufferRef with your format, timing and block buffer.

Hope this helps, 

Regards, 
Djavan

**Comment by Cashews54** [comment]
Djavan,

I've done all those steps as you described but it still doesn't work.  I think if I'm messing up any part of the process it could be the CMSampleTimingInfo part.  How should I be creating the timing info?  

I've also tried using VTDecompressionSession since AVSampleBufferDisplayLayer hadn't worked for several days.  With VTDecompression I get an error when decompressing the frame, error "kVTVideoDecoderBadDataErr = -12909", so I thought it might have to do with emulation prevention bytes or some sort of byte padding that I should be ignoring.

I could post my code if that would help, but it might be a lot for you to read through.
Thanks for your time!

**Comment by djavan-bertrand** [comment]
Cashews54, 

Don't bother with the TimingInfo, display the frame immediately as we can't ensure the timing they are received.
To do that, set kCMSampleAttachmentKey_DisplayImmediately to attachments of your sample buffer.

As far as I can remember, your error is due to a bad sample buffer. This can be caused by either a wrong format description or a wrong block buffer.

Be sure to create a format description only when the frame is an i-frame, and save this format for the following p-frames.
To create the format description : 
* sps and pps should be given without their headers
* sizes should be given without headers

To create the block buffer : 
* if the frame is an i-frame, remove sps and pps from your byte buffer
* replace the header with the length of the byte buffer without the header (=> - 4)
* create your block buffer with 
    * your memoryBlock = your byte buffer
    * blockLength = size of your memory block
    * offsetToData = 0 if you passed a block buffer only containing the frame data and its header
    * dataLength = the frame data + its header length (if you passed a block buffer only containing the frame data and its header => it is the same value than blockLenght)

Did you check the OSStatus values in return of your create calls in order to narrow the problem ?

**Comment by Cashews54** [comment]
I've been checking my OSStatus values every time I run my code, and I know that there are no errors when creating the SPS/PPS format descriptions, the block buffers or the sample buffers.  The only error I get is from VTDecompression when decompressing a frame.  (Perhaps my problem has to do with the attachments to my sample buffer, so I'll try kCMSampleAttachmentKey_DisplayImmediately.) 

I have already tried everything I can think of with changing the blockLength, offsetToData, dataLength etc.  I might be making a silly error elsewhere in my code.  I'll give it another try, thanks for your time!

**Comment by vignesh02** [comment]
Hi Djavan-bertrand,

I have Bebop sample code(spiderkeys) for takeoff, land off, send pilot command and take picture in C++ and seen you Bebop C code for video streaming. I trying to migrate integrate the C code to existing C++ Code but facing lot of issue. Will be able to migrate your C to C++ for video streaming in future.

**Comment by djavan-bertrand** [comment]
Hi vignesh02, 

Migration of the SDK to C++ is not in our roadmap for the moment, sorry.

Best regards, 
Djavan

**Comment by tuxpeppe** [comment]
Hi Guys,

I installed the sdk and succesfully compiled the sample source. Sadly when i try to execute the code i got the following error:

[ERR] BebopDroneReceiveStream | 16:56:08:557 | ardiscoveryConnect:411 - Error while opening discovery connection : Socket access permission denied


Seems that something in the network address or port is wrong... i try to ping the drone at the configured ip address and the drone responde. Please can you suggest me some solution or idea to perform debug?

All the best

**Comment by 343max** [comment]
Does somebody have an implementation of the video streaming somewhere out there? It's a shame Parrot isn't simply releasing their own implementation. I would like to play around with the drone on iOS but it's seems to be very painful to just get something "simple" as streaming the video to run. Would be nice if we did not have to reinvent everything on our own. @Cashews54 any chance you could publish your progress so far. I would like to try to contribute a bit.

**Comment by donfonvon** [comment]
Hi tuxpeppe ,

I have the same problem ardiscoveryConnect socket error but for the jumping sumo. Did you find any solution? My sumo suddenly stopped operating correctly. The wifi ap seems to work, I can connect to it but running the samples gives me the socket error. Of course the android app just says about the connection problem but not the actual error i.e. the "Socket access permission denied".
Thanks

**Comment by lwyeluo** [comment]
Hi Guys,

I successfully compiled the SDK. When I execute code in Sample, I got a error named "Socket access permission denied". I had modified the JS_IP_ADDRESS, But the error is still there. Is Anyone knows how to solve it?

Thanks.
