### ISSUE TITLE
Video Streaming from Sky controller

### ISSUE THREAD

**Issue by heitzek** [ARDroneSDK3/Samples#8]
I noticed that when I connect from one station to the parrot bebop I can’t connect from any other device, so I can’t have video streaming and manual control at the same time.

However, I’ve seen that with sky controller is possible (I have one), so I suppose that what I have to do if i want to do that is get the streaming from the sky controller as the original software does.  I changed the ports to the response given by the json discovery service. But yet nothing happens.

Can you help?

**Comment by djavan-bertrand** [comment]
Hello heitzek.

Yes, you're right, you can't connect with two "normal" devices to one bebop.

To do that through the SkyController, and considering your SkyController and Bebop are already connected between each other : 
* first, you'll need to init stream data buffers for the video (see the sample Unix/JumpingSumoReceiveStream, with fragmentSize = 128 and fragment number = 1000 (instead of 65000 and 4)).
* Then you'll have to connect to the SkyController (ip : 192.168.43.1 port : 43210) (with commands buffer => see Unix/JumpingSumoChangePosture example).
* Then, when you receive the callback skycontroller_devicestate_connexionchanged_callback, you can start the video stream receiving thread (see Unix/JumpingSumoReceiveStream). 
* Now you can send the command ARDrone3DeviceController_SendMediaStreamingVideoEnable to the drone 

Finally you'll get the frames in the frameCompleteCallback.

Hope this helps, 
Djavan

**Comment by aiden56** [comment]
Hi @djavan-bertrand,

We've been working on trying to get video streaming working from the bebop to OSX for a couple of days. We've installed everything required - what changes (other than the IP address) do we need to make to receive the Bebop video feed from the JS example given? If we just change the IP, we get:

"ARNETWORK_Receiver_ThreadRun:265 - data received, error: Insufficient free space in the buffer"

Thanks,
Aiden.

**Comment by djavan-bertrand** [comment]
Hi Aiden, 

Basically, you'll have to follow my previous post, skipping all that is related to the SkyController.

So you need to init stream data buffers for the video (see the sample Unix/JumpingSumoReceiveStream, with fragmentSize = 1000 and fragment number = 128 (instead of 65000 and 4)).

And don't forget to change the command ARCOMMANDS_Generator_GenerateJumpingSumoMediaStreamingVideoEnable with ARDrone3DeviceController_SendMediaStreamingVideoEnable.

A working example will showing how to handle Bebop video stream will come before the end of the week.

Best regards,
Djavan

**Comment by aiden56** [comment]
Thanks @djavan-bertrand! I've made some progress and the frame callback is now called - however the jpeg files it outputs are all 'corrupted', nor will it stream to ffplay.

**Comment by djavan-bertrand** [comment]
Ok, my bad, I forgot this part :p
The frames are h264 encoded, not mjpeg.

**Comment by aiden56** [comment]
Great, got it! Thanks!

**Comment by pierrezurek** [comment]
Hi, you can check the following example here https://github.com/pierrezurek/Samples/tree/master/Unix/BebopDroneReceiveStream.

**Comment by heitzek** [comment]
Hi djavan!! Thanks for all help you brought, but about skycontroller still is not working, I think I do everything you said but still not getting frames.

I can connnect, I send commands and I receive their callbacks, but stream doesn't happen.

On your answer you said:

[...]

Yes, you're right, you can't connect with two "normal" devices to one bebop.

To do that through the SkyController, and considering your SkyController and Bebop are already connected between each other :

first, you'll need to init stream data buffers for the video (see the sample Unix/JumpingSumoReceiveStream, with fragmentSize = 1000 and fragment number = 128 (instead of 65000 and 4)).

--> That I did.

Then you'll have to connect to the SkyController (ip : 192.168.43.1 port : 43210) (with commands buffer => see Unix/JumpingSumoChangePosture example).

--> That I also did

Then, when you receive the callback skycontroller_devicestate_connexionchanged_callback, you can start the video stream receiving thread (see Unix/JumpingSumoReceiveStream).

-->  To keep it as simple as possible during debug, I removed the stream receiving therad and saving frames (well, just dropping them).

Now you can send the command ARDrone3DeviceController_SendMediaStreamingVideoEnable to the drone

--> This is the point I think I miss, on Unix SDK is nothing like that function you mention, it is however on iOS, I send the ARCOMMANDS_Generator_GenerateARDrone3MediaStreamingVideoEnable, but it won't send the stream back.

Finally you'll get the frames in the frameCompleteCallback.

Well, I'm not :)

Hope this helps, 
Djavan


--> It did, but I just need a bit more, could you please?

This is the NON working code.  It compiles but nothing else.

This is the debug output I get:


https://dl.dropboxusercontent.com/u/6979137/skyControllerStreamingClient.zip

**Comment by djavan-bertrand** [comment]
I tried today : 
The thing I missed is that you need send the command allStates : 
ARCOMMANDS_Generator_GenerateCommonCommonAllStates

To sum up : 
On the new Sample Unix/BebopDroneReceiveStream you will need to :
* Change ip address with 192.168.43.1 and port with 43210
* Change C2D port with 35412
* Before the call to sendBeginStream, send the all states command

And it should work !

Enjoy :)

Djavan
